FROM {{ namespace }}/{{ image_prefix }}openvswitch-ovn-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block openvswitch_ovn_sb_db_server_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_openvswitch_extend_start
COPY start_sb_db_server.sh /usr/local/bin/start-sb-db-server
RUN chmod 755 /usr/local/bin/kolla_openvswitch_extend_start \
              /usr/local/bin/start-sb-db-server

{% block openvswitch_ovn_sb_db_server_footer %}{% endblock %}
{% block footer %}{% endblock %}
