FROM {{ namespace }}/{{ image_prefix }}openvswitch-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block openvswitch_ovn_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set openvswitch_ovn_base_packages = [
        'openvswitch-ovn-common',
        'openvswitch-ovn-central',
        'openvswitch-ovn-host'
    ] %}

{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set openvswitch_ovn_base_packages = [
        'ovn-common',
        'ovn-central',
        'ovn-host'
    ] %}

{% endif %}
{{ macros.install_packages(openvswitch_ovn_base_packages | customizable("packages")) }}

{% block openvswitch_ovn_base_footer %}{% endblock %}
